import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#1bc47d',
  },
  leftImage: {
    marginLeft: 20,
    marginTop: 20,
    width: 20,
    height: 20,
  },
  bottomBox: {
    backgroundColor: '#fff',
    height: '90%',
    width: '100%',
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    paddingTop: 20,
    flexDirection: 'column',
    alignSelf: 'flex-end',
  },
  createText: {
    fontFamily: 'Gilroy-Bold',
    alignSelf: 'center',
    fontSize: 21,
    color: '#000',
  },
  fullNameView: {
    width: '87.5%',
    alignSelf: 'center',
    marginTop: 20,
    marginBottom: 7,
  },
  fullNameText: {
    color: '#000',
    fontFamily: 'Gilroy-Bold',
    fontSize: 10,
  },
  textFieldView: {
    width: '88%',
    height: 50,
    borderRadius: 3,
    borderColor: '#fefefe',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 23,
    alignSelf: 'center',
  },
  focusedTextFieldView: {
    width: '88%',
    height: 50,
    borderRadius: 3,
    borderColor: '#1bc47d',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 23,
    alignSelf: 'center',
  },
  subNameFieldView: {
    width: '45%',
    height: 50,
    borderRadius: 3,
    borderColor: '#fefefe',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  focusedSubNameFieldView: {
    width: '45%',
    height: 50,
    borderRadius: 3,
    borderColor: '#1bc47d',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  numberViewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'center',
    marginBottom: 23,
  },
  dialCodeView: {
    borderColor: '#1bc47d',
    width: 68,
    height: 50,
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'space-around',
    flexDirection: 'row',
  },
  dialCodeText: {
    color: '#000',
    fontSize: 11,
    fontFamily: 'Gilroy-Regular',
  },
  focusedNumberFieldView: {
    width: '60%',
    height: 50,
    borderRadius: 3,
    borderColor: '#1bc47d',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  numberFieldView: {
    width: '60%',
    height: 50,
    borderRadius: 3,
    borderColor: '#fefefe',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  textFieldInput: {
    width: '100%',
    height: 45,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#000',
    fontSize: 16,
    fontFamily: 'Gilroy-Semibold',
    paddingLeft: -1,
  },
  continueView: {
    width: '87.5%',
    height: 42,
    backgroundColor: '#1BC47D',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
    alignSelf: 'center',
    borderRadius: 3,
    marginBottom: 10,
  },
  continueText: {
    color: '#fff',
    fontFamily: 'Gilroy-Bold',
    fontSize: 13,
  },
});
